[build]
  command = "curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.0-stable.tar.xz | tar xJ && export PATH=$PATH:`pwd`/flutter/bin && flutter build web --no-tree-shake-icons"
  publish = "build/web"
